### ISSUE TITLE
generate mongose schema from swagger.yaml

### ISSUE THREAD

**Issue by cosentino** [Eskalol/generator-swagger-es-6#15]
Hi,
is there a command to also generate the content of "new mongoose.Schema({...})" from the info contained in swager.yaml?
I've noticed that the exemple model person.js already contains the schema, but the models generated with "yo swagger-es-6:model" doesen't.
Thanks

**Comment by Eskalol** [comment]
The Person model is just an example of usage :).
Well the model generator does only create a model file in correct directory and a test file, so thats pretty much what it does. But your idea of generating the schema through a swagger definition in the swagger.yaml is really exciting. I will create a new issue for it!
I don't think I have time to implement it within the next few days so it will be free to grab.

**Comment by Eskalol** [comment]
See #16

**Comment by cosentino** [comment]
Understood, thank you.

**Comment by Eskalol** [comment]
Thank you for feedback! don't hesitate to ask more questions 😄
