### ISSUE TITLE
yo swagger-es-6:controller does not create a route.

### ISSUE THREAD

**Issue by sebastiaorealino** [Eskalol/generator-swagger-es-6#7]
When i create a new controller, the controller was ben create but its route does not.

**Comment by Eskalol** [comment]
Yeah, the routings has to be specified in the swagger yaml file, then the swagger middleware will take care of the routing for you. I planned to create a swagger yaml generator too, but it was much more tricky than I thought. Thats why you are being prompted with route when generating a new controller.

**Comment by sebastiaorealino** [comment]
Ahn ok! 
I'll use it here and try to collaborate with you.
Thanks for the answer.

**Comment by Eskalol** [comment]
Thank you for feedback  don't hesitate to open more issues about convenience, bugs or suggestions etc.. . :)

**Comment by Eskalol** [comment]
I think I can close this one now.
